[package]
name = "show"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
camino = "1.0.9"
clap = { version = "3.1.18", features = ["derive"] }
datafusion = { version = "8.0.0", features = ["avro"] }
tokio = "1.0"
